name: Snyk Reachability Test

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  snyk-os-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_API: https://api.snyk.io
        run: snyk auth "$SNYK_TOKEN"

      - name: Generate SBOM (CycloneDX JSON)
        env:
          SNYK_API: https://api.snyk.io
        run: |
          snyk sbom --org=bb34b202-b76c-4e32-bba2-23b970d74f04 --format=cyclonedx1.5+json --all-projects > sbom.json

      - name: Test SBOM with reachability and parse output
        id: snyk-test
        env:
          SNYK_API: https://api.snyk.io
        run: |
          echo "🔍 Snyk Open Source analysis..."
          echo ""
          
          # Run Snyk SBOM test and capture output with proper exit code handling
          set +e  # Don't exit on error, we'll handle it manually
          SNYK_OUTPUT=$(snyk sbom test --experimental --org=bb34b202-b76c-4e32-bba2-23b970d74f04 --file=sbom.json --reachability 2>&1)
          EXIT_CODE=$?
          set -e  # Re-enable exit on error
          
          # Display the raw Snyk output first
          echo "📋 SNYK SBOM REACHABILITY ANALYSIS"
          echo "=================================="
          echo ""
          echo "$SNYK_OUTPUT"
          echo ""
          
          # Parse the output for reachable vulnerabilities
          echo "📊 PARSED VULNERABILITY SUMMARY"
          echo "───────────────────────────────"
          
          # Count total vulnerabilities from the summary section
          TOTAL_VULNS=$(echo "$SNYK_OUTPUT" | grep -o 'Total security issues: [0-9]\+' | grep -o '[0-9]\+' || echo "0")
          
          # Count reachable vulnerabilities by looking for "Reachability: Reachable" pattern
          REACHABLE_VULNS=$(echo "$SNYK_OUTPUT" | grep -c "Reachability: Reachable" || echo "0")
          
          # Count unreachable vulnerabilities by looking for "No reachable path found" pattern
          UNREACHABLE_VULNS=$(echo "$SNYK_OUTPUT" | grep -c "No reachable path found" || echo "0")
          
          echo "🔍 Total vulnerabilities found: $TOTAL_VULNS"
          echo "🎯 Reachable vulnerabilities: $REACHABLE_VULNS"
          echo "🔒 Unreachable vulnerabilities: $UNREACHABLE_VULNS"
          echo ""
          
          if [ "$REACHABLE_VULNS" -gt 0 ]; then
            echo "🚨 REACHABLE VULNERABILITIES DETAILS"
            echo "────────────────────────────────────"
            
            # Extract reachable vulnerability details with better context
            echo "$SNYK_OUTPUT" | grep -B 10 -A 2 "Reachability: Reachable" | grep -E "(CRITICAL|HIGH|MEDIUM|LOW|Finding ID)" | head -20
            echo ""
            
            # Count by severity for reachable vulnerabilities - look for severity in the lines before "Reachability: Reachable"
            CRITICAL=$(echo "$SNYK_OUTPUT" | grep -B 10 "Reachability: Reachable" | grep -c "\[CRITICAL\]" || echo "0")
            HIGH=$(echo "$SNYK_OUTPUT" | grep -B 10 "Reachability: Reachable" | grep -c "\[HIGH\]" || echo "0")
            MEDIUM=$(echo "$SNYK_OUTPUT" | grep -B 10 "Reachability: Reachable" | grep -c "\[MEDIUM\]" || echo "0")
            LOW=$(echo "$SNYK_OUTPUT" | grep -B 10 "Reachability: Reachable" | grep -c "\[LOW\]" || echo "0")
            
            echo "📈 REACHABLE VULNERABILITIES BY SEVERITY"
            echo "────────────────────────────────────────"
            echo "🔴 Critical: $CRITICAL"
            echo "🟠 High: $HIGH"
            echo "🟡 Medium: $MEDIUM"
            echo "🟢 Low: $LOW"
            echo ""
          else
            echo "✅ No reachable vulnerabilities found!"
            echo "All detected vulnerabilities are not reachable in your codebase."
            echo ""
          fi
          
          # Create GitHub step summary
          echo "## 🔍 Snyk Reachability Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Vulnerability Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Total vulnerabilities found:** $TOTAL_VULNS" >> $GITHUB_STEP_SUMMARY
          echo "- **Reachable vulnerabilities:** $REACHABLE_VULNS" >> $GITHUB_STEP_SUMMARY
          echo "- **Unreachable vulnerabilities:** $UNREACHABLE_VULNS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "$REACHABLE_VULNS" -gt 0 ]; then
            echo "### 🚨 Reachable Vulnerabilities by Severity" >> $GITHUB_STEP_SUMMARY
            echo "- 🔴 **Critical:** $CRITICAL" >> $GITHUB_STEP_SUMMARY
            echo "- 🟠 **High:** $HIGH" >> $GITHUB_STEP_SUMMARY
            echo "- 🟡 **Medium:** $MEDIUM" >> $GITHUB_STEP_SUMMARY
            echo "- 🟢 **Low:** $LOW" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            echo "### 📋 Raw Snyk Output" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "$SNYK_OUTPUT" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "### ✅ No Reachable Vulnerabilities" >> $GITHUB_STEP_SUMMARY
            echo "All detected vulnerabilities are not reachable in your codebase." >> $GITHUB_STEP_SUMMARY
          fi
          
          # Handle exit codes properly - Snyk exit codes: 0=success, 1=vulnerabilities found, 2=command failed
          if [ "$EXIT_CODE" = "2" ]; then
            echo "❌ Snyk command failed to execute (exit code 2). This indicates a command execution error."
            echo "💡 Try re-running the workflow or check the Snyk service status."
            echo "🔧 Use -d flag for debug logs if this persists."
            exit 2
          elif [ "$EXIT_CODE" = "1" ]; then
            echo "✅ Snyk completed successfully - vulnerabilities found (exit code 1)"
          elif [ "$EXIT_CODE" = "0" ]; then
            echo "✅ Snyk completed successfully - no vulnerabilities found (exit code 0)"
          else
            echo "⚠️  Snyk completed with unexpected exit code: $EXIT_CODE"
            exit "$EXIT_CODE"
          fi
# Optional - upload the SBOM results as an artifact
      # - name: Upload SBOM as artifact
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: snyk-sbom-reachability-results
      #     path: sbom.json
      #     retention-days: 30

